### ISSUE TITLE
Investigate whether this move-contact job ever executed

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#220]
https://users-chis-ke.app.medicmobile.org/board/queue/MOVE_CONTACT_QUEUE/8414b9ba-e3b4-4d00-ad74-822d57452365?status=completed

Did this execute? Logs seem to just indicate that it was delayed because of sentinel backlog for 2 days and maybe nothing ever happened?

Nairobi backlog has been kinda wild for many days, so we probably did well not to execute the job
![Image](https://github.com/user-attachments/assets/421dbef9-a8cc-4d73-b018-4739572bb576)

Why is it in a completed state?  Is 2 days the right max limit (seems like no)?

**Comment by kennsippell** [comment]
A few more: 
* https://users-chis-ke.app.medicmobile.org/board/queue/MOVE_CONTACT_QUEUE/35ecba4e-b09f-4e64-92ab-01cb0cf79f68?status=completed
* https://users-chis-ke.app.medicmobile.org/board/queue/MOVE_CONTACT_QUEUE/a9c26cd6-c6ff-4d4a-a253-516e8a0894a3?status=completed

**Comment by mrjones-plip** [comment]
@kennsippell - are all three moves on the Nairobi  instance (`nairobi-echis.health.go.ke`)?

**Comment by kennsippell** [comment]
Yes. But there are 32 jobs which are delayed right now due to sentinel backlog and that spans many instances

**Comment by paulpascal** [comment]
Hi @kenn, after a quick investigation into the differents jobs referenced here, here’s what I found by reviewing the job’s execution and inspecting each job logs directly on the jobs board:

#### 1. Job Timing and Delays:
 - The first job was initiated on November 1, 2024. Two additional jobs on November 2, 2024.
 - All three jobs encountered repeated delays due to a sentinel backlog, preventing immediate execution.
 - Logs indicate retry attempts every four hours, with the first job for instance experiencing delays for up to two days.

#### 2.	Logs and Delay Details:
Below are excerpts from the logs indicating multiple postponements due to backlog thresholds not being met (first job):
```
[2024-11-01T13:13:21.440Z]: Job ID postponed until 5:13 PM.  Reason was sentinel backlog.
[2024-11-01T17:13:22.265Z]: Job ID postponed until 9:13 PM.  Reason was sentinel backlog.
...
[2024-11-03T05:13:28.461Z]: Job ID postponed until 9:13 AM.  Reason was sentinel backlog.
```

#### 3.	Job Completion Status:
 - After the delay period, the jobs were marked as completed—hence its status showing as “completed” in the system.
 - I went ahead to double-check the contacts (of the 3 jobs) intended to be moved, confirming they were successfully moved to the new areas.

It seems that the partner may have been unaware of the final timing of these contact moves due to the delays, leading to the assumption that the contacts were not moved. However, once the backlog was cleared, the system processed the moves, albeit at a later time.

**Comment by paulpascal** [comment]
Hi @kenn, after a quick investigation into the differents jobs referenced here, here’s what I found by reviewing the job’s execution and inspecting each job logs directly on the jobs board:

#### 1. Job Timing and Delays:
 - The first job was initiated on November 1, 2024. The two others jobs on November 2, 2024.
 - All three jobs encountered repeated delays due to a sentinel backlog, preventing immediate execution.
 - Logs indicate retry attempts every four hours, with the first job for instance experiencing delays for up to two days.

#### 2.	Logs and Delay Details:
Below are excerpts from the logs indicating multiple postponements due to backlog thresholds not being met (first job) until the 3 of November:
```
[2024-11-01T13:13:21.440Z]: Job ### postponed until 5:13 PM.  Reason was sentinel backlog.
[2024-11-01T17:13:22.265Z]: Job ### postponed until 9:13 PM.  Reason was sentinel backlog.
...
[2024-11-03T05:13:28.461Z]: Job ### postponed until 9:13 AM.  Reason was sentinel backlog.
```

#### 3.	Job Completion Status:
 - After the delay period, the jobs were marked as completed—hence its status showing as “completed” in the system.
 - I went ahead to double-check the contacts (of the 3 jobs) intended to be moved, confirming they were successfully moved to the new areas.

**It seems that the partner may have been unaware of the final timing of these contact moves due to the delays (preventing the execution), leading to the assumption that the contacts were not moved. However, once the backlog was cleared, the system processed the moves, albeit at a later time.** 



cc: @mrjones-plip

**Comment by kennsippell** [comment]
ic. Seems the logs are truncated. Do you know a way to see the full log for a job?

**Comment by paulpascal** [comment]
Yes i truncated it myself, but on the board you can see the logs of each job, in the `Logs` tab.


![Image](https://github.com/user-attachments/assets/c42ed04f-7f24-40f8-af94-8c773c3779c8)

**Comment by paulpascal** [comment]
One other way I use to grab the logs 

```
kubectl --context arn:aws:eks:eu-west-2:720541322708:cluster/prod-cht-eks  --namespace users-chis-prod logs deploy/users-chis-ke-cht-user-management-worker --since 8h
```

**Comment by kennsippell** [comment]
Oh. Is the output from cht-conf not included in the job's logs? Should it be? Perhaps that was my source of confusion.

**Comment by paulpascal** [comment]
Oh no, its not included in the job own logs.

> Should it be

I think so, 

> Perhaps that was my source of confusion.

This logs are currently available only from the worker logs

**Comment by kenn** [comment]
> Hi [@kenn](https://github.com/kenn), after a quick investigation into the differents jobs referenced here, here’s what I found by reviewing the job’s execution and inspecting each job logs directly on the jobs board:

Would appreciate if you'd mention the right person correctly. Thanks!
